name: Build MSIX Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-msix:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 8
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Build MSIX package
      run: pnpm run build-msix
    
    - name: Upload MSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: hugo-manager-msix
        path: dist/*.appx
        retention-days: 30
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/*.appx
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
